apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ci0254wbs-dotnet-basic
  janus-idp.io/tekton: ci0254wbs-dotnet-basic
  backstage.io/kubernetes-id: ci0254wbs-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ci0254wbs-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
